name: oidc-smoke
on: { workflow_dispatch: {} }

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    permissions: { id-token: write, contents: read }
    steps:
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show account
        run: az account show

      - name: Can read backend container?
        run: az storage container show --name ${{ vars.STATE_CONTAINER }} --account-name ${{ vars.STATE_STORAGE }} --auth-mode login
